name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/connect-wallets ]
  pull_request:
    branches: [ main, master, feature/connect-wallets ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Xvfb
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &    
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx playwright test
    - name: Upload Playwright videos
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-videos
        path: test-results/**/*.webm
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
